apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
data:
  credentials: |-
    [default]
    aws_access_key_id = test_id
    aws_secret_access_key = test_key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcloud-config
data:
  service-account-keys.json: |-
    {
      "type": "authorized_user",
      "client_id": "your_id.apps.googleusercontent.com",
      "client_secret": "your_secret",
      "refresh_token": "your_token"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - env:
            - name: AWS_ATHENA_DB_NAME
              value: your-athena-db-name
            - name: AWS_ATHENA_DB_TABLE
              value: your-athena-db-table
            - name: AWS_ATHENA_QUERY_RESULT_LOCATION
              value: s3://your-athena-query-results-location
            - name: AWS_ATHENA_REGION
              value: your-athena-region
            - name: AWS_BILLING_ACCOUNT_ID
              value: your-billing-account-id
            - name: AWS_BILLING_ACCOUNT_NAME
              value: your-billing-account-name
            - name: AWS_TARGET_ACCOUNT_ROLE_NAME
              value: your-proxy-role-name
            - name: AWS_USE_BILLING_DATA
              value: "true"
            - name: AZURE_CLIENT_ID
              value: your-azure-client-id
            - name: AZURE_CLIENT_SECRET
              value: your-azure-client-secret
            - name: AZURE_TENANT_ID
              value: your-azure-tenant-id
            - name: AZURE_USE_BILLING_DATA
              value: "true"
            - name: GCP_BIG_QUERY_TABLE
              value: your-billing-export-table
            - name: GCP_BILLING_PROJECT_ID
              value: your-billing-account-id
            - name: GCP_BILLING_PROJECT_NAME
              value: your-billing-account-name
            - name: GCP_USE_BILLING_DATA
              value: "true"
            - name: GCP_USE_CARBON_FREE_ENERGY_PERCENTAGE
              value: "true"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/.config/gcloud/service-account-keys.json
          image: esara/cloudcarbonfootprint-api
          name: api
          ports:
            - containerPort: 4000
          volumeMounts:
            - mountPath: /root/.aws/credentials
              name: aws-volume
            - mountPath: /root/.config/gcloud/service-account-keys.json
              name: gcloud-volume
      restartPolicy: Always
      volumes:
        - name: aws-volume
          configMap:
            name: aws-config
        - name: gcloud-volume
          configMap:
            name: gcloud-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: api
  name: api
spec:
  ports:
    - name: api
      port: 4000
  selector:
    app.kubernetes.io/name: api
