---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
data:
  default.conf: |-
      server {
        listen 80;
        include /etc/nginx/mime.types;
        root /var/www;
        index index.html index.htm;
        location /api {
          resolver 10.100.0.10;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://api.cloud-carbon-footprint.svc.cluster.local:4000$request_uri;
        }
        location / {
          try_files $uri $uri/ =404;
        }
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: client
    spec:
      containers:
        - image: esara/cloudcarbonfootprint-client
          name: client
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: client-volume
      restartPolicy: Always
      volumes:
        - name: client-volume
          configMap:
            name: client-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: client
  name: client
spec:
  ports:
    - name: client
      port: 80
  selector:
    app.kubernetes.io/name: client
