apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - image: esara/cloudcarbonfootprint-mock
          name: api
          ports:
            - containerPort: 4000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: api
  name: api
spec:
  ports:
    - name: api
      port: 4000
  selector:
    app.kubernetes.io/name: api
